#
# Find the GOOGLE Utils library
#
# This module defines
message(STATUS "Google tools :${GOOGLETOOLS_INCLUDE_PATH} ${GOOGLETOOLS_LIBRARY_PATH}")
find_path(GOOGLEPROF_INCLUDE_DIR google/profiler.h
  PATHS ${GOOGLETOOLS_INCLUDE_PATH} NO_DEFAULT_PATH)

find_library(GOOGLEPROF_LIBRARY profiler
  PATHS ${GOOGLETOOLS_LIBRARY_PATH} NO_DEFAULT_PATH)

find_library(UNWIND_LIBRARY unwind
  PATHS ${UNWIND_LIBRARY_PATH} )
  
set(GOOGLEPROF_FOUND "NO")
if(GOOGLEPROF_INCLUDE_DIR AND GOOGLEPROF_LIBRARY)
  set(GOOGLEPROF_FOUND "YES")
  set(GOOGLEPROF_LIBRARIES ${GOOGLEPROF_LIBRARY} ${UNWIND_LIBRARY})
  set(GOOGLEPROF_INCLUDE_DIRS ${GOOGLEPROF_INCLUDE_DIR})
endif(GOOGLEPROF_INCLUDE_DIR AND GOOGLEPROF_LIBRARY)
list(APPEND REQUIRED_DEPENDENCIES GOOGLEPROF)
