########## MACROS ###########################################################################
#############################################################################################

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


########### FOUND PACKAGE ###################################################################
#############################################################################################

include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated FindOpenEXR.cmake")
set(OpenEXR_FOUND 1)
set(OpenEXR_VERSION "2.5.7")

find_package_handle_standard_args(OpenEXR REQUIRED_VARS
                                  OpenEXR_VERSION VERSION_VAR OpenEXR_VERSION)
mark_as_advanced(OpenEXR_FOUND OpenEXR_VERSION)

set(OpenEXR_COMPONENTS OpenEXR::IlmImfUtil OpenEXR::IlmImf OpenEXR::IlmImfConfig OpenEXR::ilmbase_conan_pkgconfig OpenEXR::IMath OpenEXR::Half OpenEXR::IexMath OpenEXR::IlmThread OpenEXR::Iex OpenEXR::IlmBaseConfig)

if(OpenEXR_FIND_COMPONENTS)
    foreach(_FIND_COMPONENT ${OpenEXR_FIND_COMPONENTS})
        list(FIND OpenEXR_COMPONENTS "OpenEXR::${_FIND_COMPONENT}" _index)
        if(${_index} EQUAL -1)
            conan_message(FATAL_ERROR "Conan: Component '${_FIND_COMPONENT}' NOT found in package 'OpenEXR'")
        else()
            conan_message(STATUS "Conan: Component '${_FIND_COMPONENT}' found in package 'OpenEXR'")
        endif()
    endforeach()
endif()

########### VARIABLES #######################################################################
#############################################################################################


set(OpenEXR_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_RES_DIRS )
set(OpenEXR_DEFINITIONS )
set(OpenEXR_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(OpenEXR_COMPILE_DEFINITIONS )
set(OpenEXR_COMPILE_OPTIONS_LIST "" "")
set(OpenEXR_COMPILE_OPTIONS_C "")
set(OpenEXR_COMPILE_OPTIONS_CXX "")
set(OpenEXR_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(OpenEXR_LIBRARIES "") # Will be filled later
set(OpenEXR_LIBS "") # Same as OpenEXR_LIBRARIES
set(OpenEXR_SYSTEM_LIBS )
set(OpenEXR_FRAMEWORK_DIRS )
set(OpenEXR_FRAMEWORKS )
set(OpenEXR_FRAMEWORKS_FOUND "") # Will be filled later
set(OpenEXR_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")

conan_find_apple_frameworks(OpenEXR_FRAMEWORKS_FOUND "${OpenEXR_FRAMEWORKS}" "${OpenEXR_FRAMEWORK_DIRS}")

mark_as_advanced(OpenEXR_INCLUDE_DIRS
                 OpenEXR_INCLUDE_DIR
                 OpenEXR_INCLUDES
                 OpenEXR_DEFINITIONS
                 OpenEXR_LINKER_FLAGS_LIST
                 OpenEXR_COMPILE_DEFINITIONS
                 OpenEXR_COMPILE_OPTIONS_LIST
                 OpenEXR_LIBRARIES
                 OpenEXR_LIBS
                 OpenEXR_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to OpenEXR_LIBS and OpenEXR_LIBRARY_LIST
set(OpenEXR_LIBRARY_LIST IlmImfUtil-2_5 IlmImf-2_5 Imath-2_5 Half-2_5 IexMath-2_5 IlmThread-2_5 Iex-2_5)
set(OpenEXR_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_OpenEXR_DEPENDENCIES "${OpenEXR_FRAMEWORKS_FOUND} ${OpenEXR_SYSTEM_LIBS} ZLIB::ZLIB")

conan_package_library_targets("${OpenEXR_LIBRARY_LIST}"  # libraries
                              "${OpenEXR_LIB_DIRS}"      # package_libdir
                              "${_OpenEXR_DEPENDENCIES}"  # deps
                              OpenEXR_LIBRARIES            # out_libraries
                              OpenEXR_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "OpenEXR")                                      # package_name

set(OpenEXR_LIBS ${OpenEXR_LIBRARIES})

foreach(_FRAMEWORK ${OpenEXR_FRAMEWORKS_FOUND})
    list(APPEND OpenEXR_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND OpenEXR_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${OpenEXR_SYSTEM_LIBS})
    list(APPEND OpenEXR_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND OpenEXR_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(OpenEXR_LIBRARIES_TARGETS "${OpenEXR_LIBRARIES_TARGETS};ZLIB::ZLIB")
set(OpenEXR_LIBRARIES "${OpenEXR_LIBRARIES};ZLIB::ZLIB")

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})


########### COMPONENT IlmBaseConfig VARIABLES #############################################

set(OpenEXR_IlmBaseConfig_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmBaseConfig_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmBaseConfig_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmBaseConfig_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IlmBaseConfig_RES_DIRS )
set(OpenEXR_IlmBaseConfig_DEFINITIONS )
set(OpenEXR_IlmBaseConfig_COMPILE_DEFINITIONS )
set(OpenEXR_IlmBaseConfig_COMPILE_OPTIONS_C "")
set(OpenEXR_IlmBaseConfig_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IlmBaseConfig_LIBS )
set(OpenEXR_IlmBaseConfig_SYSTEM_LIBS )
set(OpenEXR_IlmBaseConfig_FRAMEWORK_DIRS )
set(OpenEXR_IlmBaseConfig_FRAMEWORKS )
set(OpenEXR_IlmBaseConfig_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_IlmBaseConfig_DEPENDENCIES )
set(OpenEXR_IlmBaseConfig_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Iex VARIABLES #############################################

set(OpenEXR_Iex_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Iex_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Iex_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Iex_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_Iex_RES_DIRS )
set(OpenEXR_Iex_DEFINITIONS )
set(OpenEXR_Iex_COMPILE_DEFINITIONS )
set(OpenEXR_Iex_COMPILE_OPTIONS_C "")
set(OpenEXR_Iex_COMPILE_OPTIONS_CXX "")
set(OpenEXR_Iex_LIBS Iex-2_5)
set(OpenEXR_Iex_SYSTEM_LIBS )
set(OpenEXR_Iex_FRAMEWORK_DIRS )
set(OpenEXR_Iex_FRAMEWORKS )
set(OpenEXR_Iex_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_Iex_DEPENDENCIES OpenEXR::IlmBaseConfig)
set(OpenEXR_Iex_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IlmThread VARIABLES #############################################

set(OpenEXR_IlmThread_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmThread_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmThread_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmThread_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IlmThread_RES_DIRS )
set(OpenEXR_IlmThread_DEFINITIONS )
set(OpenEXR_IlmThread_COMPILE_DEFINITIONS )
set(OpenEXR_IlmThread_COMPILE_OPTIONS_C "")
set(OpenEXR_IlmThread_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IlmThread_LIBS IlmThread-2_5)
set(OpenEXR_IlmThread_SYSTEM_LIBS )
set(OpenEXR_IlmThread_FRAMEWORK_DIRS )
set(OpenEXR_IlmThread_FRAMEWORKS )
set(OpenEXR_IlmThread_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_IlmThread_DEPENDENCIES OpenEXR::IlmBaseConfig OpenEXR::Iex)
set(OpenEXR_IlmThread_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IexMath VARIABLES #############################################

set(OpenEXR_IexMath_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IexMath_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IexMath_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IexMath_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IexMath_RES_DIRS )
set(OpenEXR_IexMath_DEFINITIONS )
set(OpenEXR_IexMath_COMPILE_DEFINITIONS )
set(OpenEXR_IexMath_COMPILE_OPTIONS_C "")
set(OpenEXR_IexMath_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IexMath_LIBS IexMath-2_5)
set(OpenEXR_IexMath_SYSTEM_LIBS )
set(OpenEXR_IexMath_FRAMEWORK_DIRS )
set(OpenEXR_IexMath_FRAMEWORKS )
set(OpenEXR_IexMath_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_IexMath_DEPENDENCIES OpenEXR::IlmBaseConfig OpenEXR::Iex)
set(OpenEXR_IexMath_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT Half VARIABLES #############################################

set(OpenEXR_Half_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Half_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Half_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_Half_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_Half_RES_DIRS )
set(OpenEXR_Half_DEFINITIONS )
set(OpenEXR_Half_COMPILE_DEFINITIONS )
set(OpenEXR_Half_COMPILE_OPTIONS_C "")
set(OpenEXR_Half_COMPILE_OPTIONS_CXX "")
set(OpenEXR_Half_LIBS Half-2_5)
set(OpenEXR_Half_SYSTEM_LIBS )
set(OpenEXR_Half_FRAMEWORK_DIRS )
set(OpenEXR_Half_FRAMEWORKS )
set(OpenEXR_Half_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_Half_DEPENDENCIES OpenEXR::IlmBaseConfig)
set(OpenEXR_Half_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IMath VARIABLES #############################################

set(OpenEXR_IMath_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IMath_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IMath_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IMath_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IMath_RES_DIRS )
set(OpenEXR_IMath_DEFINITIONS )
set(OpenEXR_IMath_COMPILE_DEFINITIONS )
set(OpenEXR_IMath_COMPILE_OPTIONS_C "")
set(OpenEXR_IMath_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IMath_LIBS Imath-2_5)
set(OpenEXR_IMath_SYSTEM_LIBS )
set(OpenEXR_IMath_FRAMEWORK_DIRS )
set(OpenEXR_IMath_FRAMEWORKS )
set(OpenEXR_IMath_BUILD_MODULES_PATHS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake/conan-official-openexr-targets.cmake")
set(OpenEXR_IMath_DEPENDENCIES OpenEXR::IlmBaseConfig OpenEXR::Half OpenEXR::IexMath)
set(OpenEXR_IMath_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT ilmbase_conan_pkgconfig VARIABLES #############################################

set(OpenEXR_ilmbase_conan_pkgconfig_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include")
set(OpenEXR_ilmbase_conan_pkgconfig_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include")
set(OpenEXR_ilmbase_conan_pkgconfig_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include")
set(OpenEXR_ilmbase_conan_pkgconfig_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_ilmbase_conan_pkgconfig_RES_DIRS )
set(OpenEXR_ilmbase_conan_pkgconfig_DEFINITIONS )
set(OpenEXR_ilmbase_conan_pkgconfig_COMPILE_DEFINITIONS )
set(OpenEXR_ilmbase_conan_pkgconfig_COMPILE_OPTIONS_C "")
set(OpenEXR_ilmbase_conan_pkgconfig_COMPILE_OPTIONS_CXX "")
set(OpenEXR_ilmbase_conan_pkgconfig_LIBS )
set(OpenEXR_ilmbase_conan_pkgconfig_SYSTEM_LIBS )
set(OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORK_DIRS )
set(OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORKS )
set(OpenEXR_ilmbase_conan_pkgconfig_BUILD_MODULES_PATHS )
set(OpenEXR_ilmbase_conan_pkgconfig_DEPENDENCIES OpenEXR::IlmBaseConfig OpenEXR::Half OpenEXR::Iex OpenEXR::IexMath OpenEXR::IMath OpenEXR::IlmThread)
set(OpenEXR_ilmbase_conan_pkgconfig_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IlmImfConfig VARIABLES #############################################

set(OpenEXR_IlmImfConfig_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfConfig_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfConfig_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfConfig_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IlmImfConfig_RES_DIRS )
set(OpenEXR_IlmImfConfig_DEFINITIONS )
set(OpenEXR_IlmImfConfig_COMPILE_DEFINITIONS )
set(OpenEXR_IlmImfConfig_COMPILE_OPTIONS_C "")
set(OpenEXR_IlmImfConfig_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IlmImfConfig_LIBS )
set(OpenEXR_IlmImfConfig_SYSTEM_LIBS )
set(OpenEXR_IlmImfConfig_FRAMEWORK_DIRS )
set(OpenEXR_IlmImfConfig_FRAMEWORKS )
set(OpenEXR_IlmImfConfig_BUILD_MODULES_PATHS )
set(OpenEXR_IlmImfConfig_DEPENDENCIES )
set(OpenEXR_IlmImfConfig_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IlmImf VARIABLES #############################################

set(OpenEXR_IlmImf_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImf_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImf_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImf_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IlmImf_RES_DIRS )
set(OpenEXR_IlmImf_DEFINITIONS )
set(OpenEXR_IlmImf_COMPILE_DEFINITIONS )
set(OpenEXR_IlmImf_COMPILE_OPTIONS_C "")
set(OpenEXR_IlmImf_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IlmImf_LIBS IlmImf-2_5)
set(OpenEXR_IlmImf_SYSTEM_LIBS )
set(OpenEXR_IlmImf_FRAMEWORK_DIRS )
set(OpenEXR_IlmImf_FRAMEWORKS )
set(OpenEXR_IlmImf_BUILD_MODULES_PATHS )
set(OpenEXR_IlmImf_DEPENDENCIES OpenEXR::IlmImfConfig OpenEXR::Iex OpenEXR::Half OpenEXR::IMath OpenEXR::IlmThread ZLIB::ZLIB)
set(OpenEXR_IlmImf_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)

########### COMPONENT IlmImfUtil VARIABLES #############################################

set(OpenEXR_IlmImfUtil_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfUtil_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include;C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfUtil_INCLUDES "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/include/OpenEXR")
set(OpenEXR_IlmImfUtil_LIB_DIRS "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib")
set(OpenEXR_IlmImfUtil_RES_DIRS )
set(OpenEXR_IlmImfUtil_DEFINITIONS )
set(OpenEXR_IlmImfUtil_COMPILE_DEFINITIONS )
set(OpenEXR_IlmImfUtil_COMPILE_OPTIONS_C "")
set(OpenEXR_IlmImfUtil_COMPILE_OPTIONS_CXX "")
set(OpenEXR_IlmImfUtil_LIBS IlmImfUtil-2_5)
set(OpenEXR_IlmImfUtil_SYSTEM_LIBS )
set(OpenEXR_IlmImfUtil_FRAMEWORK_DIRS )
set(OpenEXR_IlmImfUtil_FRAMEWORKS )
set(OpenEXR_IlmImfUtil_BUILD_MODULES_PATHS )
set(OpenEXR_IlmImfUtil_DEPENDENCIES OpenEXR::IlmImfConfig OpenEXR::IlmImf)
set(OpenEXR_IlmImfUtil_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)


########## FIND PACKAGE DEPENDENCY ##########################################################
#############################################################################################

include(CMakeFindDependencyMacro)

if(NOT ZLIB_FOUND)
    find_dependency(ZLIB REQUIRED)
else()
    conan_message(STATUS "Conan: Dependency ZLIB already found")
endif()


########## FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #######################################
#############################################################################################

########## COMPONENT IlmBaseConfig FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IlmBaseConfig_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IlmBaseConfig_FRAMEWORKS_FOUND "${OpenEXR_IlmBaseConfig_FRAMEWORKS}" "${OpenEXR_IlmBaseConfig_FRAMEWORK_DIRS}")

set(OpenEXR_IlmBaseConfig_LIB_TARGETS "")
set(OpenEXR_IlmBaseConfig_NOT_USED "")
set(OpenEXR_IlmBaseConfig_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IlmBaseConfig_FRAMEWORKS_FOUND} ${OpenEXR_IlmBaseConfig_SYSTEM_LIBS} ${OpenEXR_IlmBaseConfig_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IlmBaseConfig_LIBS}"
                              "${OpenEXR_IlmBaseConfig_LIB_DIRS}"
                              "${OpenEXR_IlmBaseConfig_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IlmBaseConfig_NOT_USED
                              OpenEXR_IlmBaseConfig_LIB_TARGETS
                              ""
                              "OpenEXR_IlmBaseConfig")

set(OpenEXR_IlmBaseConfig_LINK_LIBS ${OpenEXR_IlmBaseConfig_LIB_TARGETS} ${OpenEXR_IlmBaseConfig_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT Iex FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_Iex_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_Iex_FRAMEWORKS_FOUND "${OpenEXR_Iex_FRAMEWORKS}" "${OpenEXR_Iex_FRAMEWORK_DIRS}")

set(OpenEXR_Iex_LIB_TARGETS "")
set(OpenEXR_Iex_NOT_USED "")
set(OpenEXR_Iex_LIBS_FRAMEWORKS_DEPS ${OpenEXR_Iex_FRAMEWORKS_FOUND} ${OpenEXR_Iex_SYSTEM_LIBS} ${OpenEXR_Iex_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_Iex_LIBS}"
                              "${OpenEXR_Iex_LIB_DIRS}"
                              "${OpenEXR_Iex_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_Iex_NOT_USED
                              OpenEXR_Iex_LIB_TARGETS
                              ""
                              "OpenEXR_Iex")

set(OpenEXR_Iex_LINK_LIBS ${OpenEXR_Iex_LIB_TARGETS} ${OpenEXR_Iex_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT IlmThread FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IlmThread_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IlmThread_FRAMEWORKS_FOUND "${OpenEXR_IlmThread_FRAMEWORKS}" "${OpenEXR_IlmThread_FRAMEWORK_DIRS}")

set(OpenEXR_IlmThread_LIB_TARGETS "")
set(OpenEXR_IlmThread_NOT_USED "")
set(OpenEXR_IlmThread_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IlmThread_FRAMEWORKS_FOUND} ${OpenEXR_IlmThread_SYSTEM_LIBS} ${OpenEXR_IlmThread_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IlmThread_LIBS}"
                              "${OpenEXR_IlmThread_LIB_DIRS}"
                              "${OpenEXR_IlmThread_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IlmThread_NOT_USED
                              OpenEXR_IlmThread_LIB_TARGETS
                              ""
                              "OpenEXR_IlmThread")

set(OpenEXR_IlmThread_LINK_LIBS ${OpenEXR_IlmThread_LIB_TARGETS} ${OpenEXR_IlmThread_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT IexMath FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IexMath_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IexMath_FRAMEWORKS_FOUND "${OpenEXR_IexMath_FRAMEWORKS}" "${OpenEXR_IexMath_FRAMEWORK_DIRS}")

set(OpenEXR_IexMath_LIB_TARGETS "")
set(OpenEXR_IexMath_NOT_USED "")
set(OpenEXR_IexMath_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IexMath_FRAMEWORKS_FOUND} ${OpenEXR_IexMath_SYSTEM_LIBS} ${OpenEXR_IexMath_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IexMath_LIBS}"
                              "${OpenEXR_IexMath_LIB_DIRS}"
                              "${OpenEXR_IexMath_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IexMath_NOT_USED
                              OpenEXR_IexMath_LIB_TARGETS
                              ""
                              "OpenEXR_IexMath")

set(OpenEXR_IexMath_LINK_LIBS ${OpenEXR_IexMath_LIB_TARGETS} ${OpenEXR_IexMath_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT Half FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_Half_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_Half_FRAMEWORKS_FOUND "${OpenEXR_Half_FRAMEWORKS}" "${OpenEXR_Half_FRAMEWORK_DIRS}")

set(OpenEXR_Half_LIB_TARGETS "")
set(OpenEXR_Half_NOT_USED "")
set(OpenEXR_Half_LIBS_FRAMEWORKS_DEPS ${OpenEXR_Half_FRAMEWORKS_FOUND} ${OpenEXR_Half_SYSTEM_LIBS} ${OpenEXR_Half_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_Half_LIBS}"
                              "${OpenEXR_Half_LIB_DIRS}"
                              "${OpenEXR_Half_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_Half_NOT_USED
                              OpenEXR_Half_LIB_TARGETS
                              ""
                              "OpenEXR_Half")

set(OpenEXR_Half_LINK_LIBS ${OpenEXR_Half_LIB_TARGETS} ${OpenEXR_Half_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT IMath FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IMath_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IMath_FRAMEWORKS_FOUND "${OpenEXR_IMath_FRAMEWORKS}" "${OpenEXR_IMath_FRAMEWORK_DIRS}")

set(OpenEXR_IMath_LIB_TARGETS "")
set(OpenEXR_IMath_NOT_USED "")
set(OpenEXR_IMath_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IMath_FRAMEWORKS_FOUND} ${OpenEXR_IMath_SYSTEM_LIBS} ${OpenEXR_IMath_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IMath_LIBS}"
                              "${OpenEXR_IMath_LIB_DIRS}"
                              "${OpenEXR_IMath_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IMath_NOT_USED
                              OpenEXR_IMath_LIB_TARGETS
                              ""
                              "OpenEXR_IMath")

set(OpenEXR_IMath_LINK_LIBS ${OpenEXR_IMath_LIB_TARGETS} ${OpenEXR_IMath_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/"
			"C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/lib/cmake" ${CMAKE_PREFIX_PATH})

########## COMPONENT ilmbase_conan_pkgconfig FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORKS_FOUND "${OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORKS}" "${OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORK_DIRS}")

set(OpenEXR_ilmbase_conan_pkgconfig_LIB_TARGETS "")
set(OpenEXR_ilmbase_conan_pkgconfig_NOT_USED "")
set(OpenEXR_ilmbase_conan_pkgconfig_LIBS_FRAMEWORKS_DEPS ${OpenEXR_ilmbase_conan_pkgconfig_FRAMEWORKS_FOUND} ${OpenEXR_ilmbase_conan_pkgconfig_SYSTEM_LIBS} ${OpenEXR_ilmbase_conan_pkgconfig_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_ilmbase_conan_pkgconfig_LIBS}"
                              "${OpenEXR_ilmbase_conan_pkgconfig_LIB_DIRS}"
                              "${OpenEXR_ilmbase_conan_pkgconfig_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_ilmbase_conan_pkgconfig_NOT_USED
                              OpenEXR_ilmbase_conan_pkgconfig_LIB_TARGETS
                              ""
                              "OpenEXR_ilmbase_conan_pkgconfig")

set(OpenEXR_ilmbase_conan_pkgconfig_LINK_LIBS ${OpenEXR_ilmbase_conan_pkgconfig_LIB_TARGETS} ${OpenEXR_ilmbase_conan_pkgconfig_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_PREFIX_PATH})

########## COMPONENT IlmImfConfig FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IlmImfConfig_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IlmImfConfig_FRAMEWORKS_FOUND "${OpenEXR_IlmImfConfig_FRAMEWORKS}" "${OpenEXR_IlmImfConfig_FRAMEWORK_DIRS}")

set(OpenEXR_IlmImfConfig_LIB_TARGETS "")
set(OpenEXR_IlmImfConfig_NOT_USED "")
set(OpenEXR_IlmImfConfig_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IlmImfConfig_FRAMEWORKS_FOUND} ${OpenEXR_IlmImfConfig_SYSTEM_LIBS} ${OpenEXR_IlmImfConfig_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IlmImfConfig_LIBS}"
                              "${OpenEXR_IlmImfConfig_LIB_DIRS}"
                              "${OpenEXR_IlmImfConfig_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IlmImfConfig_NOT_USED
                              OpenEXR_IlmImfConfig_LIB_TARGETS
                              ""
                              "OpenEXR_IlmImfConfig")

set(OpenEXR_IlmImfConfig_LINK_LIBS ${OpenEXR_IlmImfConfig_LIB_TARGETS} ${OpenEXR_IlmImfConfig_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_PREFIX_PATH})

########## COMPONENT IlmImf FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IlmImf_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IlmImf_FRAMEWORKS_FOUND "${OpenEXR_IlmImf_FRAMEWORKS}" "${OpenEXR_IlmImf_FRAMEWORK_DIRS}")

set(OpenEXR_IlmImf_LIB_TARGETS "")
set(OpenEXR_IlmImf_NOT_USED "")
set(OpenEXR_IlmImf_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IlmImf_FRAMEWORKS_FOUND} ${OpenEXR_IlmImf_SYSTEM_LIBS} ${OpenEXR_IlmImf_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IlmImf_LIBS}"
                              "${OpenEXR_IlmImf_LIB_DIRS}"
                              "${OpenEXR_IlmImf_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IlmImf_NOT_USED
                              OpenEXR_IlmImf_LIB_TARGETS
                              ""
                              "OpenEXR_IlmImf")

set(OpenEXR_IlmImf_LINK_LIBS ${OpenEXR_IlmImf_LIB_TARGETS} ${OpenEXR_IlmImf_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_PREFIX_PATH})

########## COMPONENT IlmImfUtil FIND LIBRARIES & FRAMEWORKS / DYNAMIC VARS #############

set(OpenEXR_IlmImfUtil_FRAMEWORKS_FOUND "")
conan_find_apple_frameworks(OpenEXR_IlmImfUtil_FRAMEWORKS_FOUND "${OpenEXR_IlmImfUtil_FRAMEWORKS}" "${OpenEXR_IlmImfUtil_FRAMEWORK_DIRS}")

set(OpenEXR_IlmImfUtil_LIB_TARGETS "")
set(OpenEXR_IlmImfUtil_NOT_USED "")
set(OpenEXR_IlmImfUtil_LIBS_FRAMEWORKS_DEPS ${OpenEXR_IlmImfUtil_FRAMEWORKS_FOUND} ${OpenEXR_IlmImfUtil_SYSTEM_LIBS} ${OpenEXR_IlmImfUtil_DEPENDENCIES})
conan_package_library_targets("${OpenEXR_IlmImfUtil_LIBS}"
                              "${OpenEXR_IlmImfUtil_LIB_DIRS}"
                              "${OpenEXR_IlmImfUtil_LIBS_FRAMEWORKS_DEPS}"
                              OpenEXR_IlmImfUtil_NOT_USED
                              OpenEXR_IlmImfUtil_LIB_TARGETS
                              ""
                              "OpenEXR_IlmImfUtil")

set(OpenEXR_IlmImfUtil_LINK_LIBS ${OpenEXR_IlmImfUtil_LIB_TARGETS} ${OpenEXR_IlmImfUtil_LIBS_FRAMEWORKS_DEPS})

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/openexr/2.5.7/_/_/package/d140711d95cc16a85766a8fc3a551dfafe84cf63/" ${CMAKE_PREFIX_PATH})


########## TARGETS ##########################################################################
#############################################################################################

########## COMPONENT IlmBaseConfig TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IlmBaseConfig)
        add_library(OpenEXR::IlmBaseConfig INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IlmBaseConfig PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IlmBaseConfig_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IlmBaseConfig PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IlmBaseConfig_LIB_DIRS}")
        set_target_properties(OpenEXR::IlmBaseConfig PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IlmBaseConfig_LINK_LIBS};${OpenEXR_IlmBaseConfig_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IlmBaseConfig PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IlmBaseConfig_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IlmBaseConfig PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IlmBaseConfig_COMPILE_OPTIONS_C};${OpenEXR_IlmBaseConfig_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Iex TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::Iex)
        add_library(OpenEXR::Iex INTERFACE IMPORTED)
        set_target_properties(OpenEXR::Iex PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_Iex_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::Iex PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_Iex_LIB_DIRS}")
        set_target_properties(OpenEXR::Iex PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_Iex_LINK_LIBS};${OpenEXR_Iex_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::Iex PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_Iex_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::Iex PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_Iex_COMPILE_OPTIONS_C};${OpenEXR_Iex_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IlmThread TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IlmThread)
        add_library(OpenEXR::IlmThread INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IlmThread PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IlmThread_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IlmThread PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IlmThread_LIB_DIRS}")
        set_target_properties(OpenEXR::IlmThread PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IlmThread_LINK_LIBS};${OpenEXR_IlmThread_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IlmThread PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IlmThread_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IlmThread PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IlmThread_COMPILE_OPTIONS_C};${OpenEXR_IlmThread_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IexMath TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IexMath)
        add_library(OpenEXR::IexMath INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IexMath PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IexMath_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IexMath PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IexMath_LIB_DIRS}")
        set_target_properties(OpenEXR::IexMath PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IexMath_LINK_LIBS};${OpenEXR_IexMath_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IexMath PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IexMath_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IexMath PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IexMath_COMPILE_OPTIONS_C};${OpenEXR_IexMath_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT Half TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::Half)
        add_library(OpenEXR::Half INTERFACE IMPORTED)
        set_target_properties(OpenEXR::Half PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_Half_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::Half PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_Half_LIB_DIRS}")
        set_target_properties(OpenEXR::Half PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_Half_LINK_LIBS};${OpenEXR_Half_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::Half PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_Half_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::Half PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_Half_COMPILE_OPTIONS_C};${OpenEXR_Half_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IMath TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IMath)
        add_library(OpenEXR::IMath INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IMath PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IMath_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IMath PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IMath_LIB_DIRS}")
        set_target_properties(OpenEXR::IMath PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IMath_LINK_LIBS};${OpenEXR_IMath_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IMath PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IMath_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IMath PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IMath_COMPILE_OPTIONS_C};${OpenEXR_IMath_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT ilmbase_conan_pkgconfig TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::ilmbase_conan_pkgconfig)
        add_library(OpenEXR::ilmbase_conan_pkgconfig INTERFACE IMPORTED)
        set_target_properties(OpenEXR::ilmbase_conan_pkgconfig PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_ilmbase_conan_pkgconfig_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::ilmbase_conan_pkgconfig PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_ilmbase_conan_pkgconfig_LIB_DIRS}")
        set_target_properties(OpenEXR::ilmbase_conan_pkgconfig PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_ilmbase_conan_pkgconfig_LINK_LIBS};${OpenEXR_ilmbase_conan_pkgconfig_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::ilmbase_conan_pkgconfig PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_ilmbase_conan_pkgconfig_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::ilmbase_conan_pkgconfig PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_ilmbase_conan_pkgconfig_COMPILE_OPTIONS_C};${OpenEXR_ilmbase_conan_pkgconfig_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IlmImfConfig TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IlmImfConfig)
        add_library(OpenEXR::IlmImfConfig INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IlmImfConfig PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IlmImfConfig_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IlmImfConfig PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IlmImfConfig_LIB_DIRS}")
        set_target_properties(OpenEXR::IlmImfConfig PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IlmImfConfig_LINK_LIBS};${OpenEXR_IlmImfConfig_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IlmImfConfig PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IlmImfConfig_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IlmImfConfig PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IlmImfConfig_COMPILE_OPTIONS_C};${OpenEXR_IlmImfConfig_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IlmImf TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IlmImf)
        add_library(OpenEXR::IlmImf INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IlmImf PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IlmImf_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IlmImf PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IlmImf_LIB_DIRS}")
        set_target_properties(OpenEXR::IlmImf PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IlmImf_LINK_LIBS};${OpenEXR_IlmImf_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IlmImf PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IlmImf_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IlmImf PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IlmImf_COMPILE_OPTIONS_C};${OpenEXR_IlmImf_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## COMPONENT IlmImfUtil TARGET #################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET OpenEXR::IlmImfUtil)
        add_library(OpenEXR::IlmImfUtil INTERFACE IMPORTED)
        set_target_properties(OpenEXR::IlmImfUtil PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                              "${OpenEXR_IlmImfUtil_INCLUDE_DIRS}")
        set_target_properties(OpenEXR::IlmImfUtil PROPERTIES INTERFACE_LINK_DIRECTORIES
                              "${OpenEXR_IlmImfUtil_LIB_DIRS}")
        set_target_properties(OpenEXR::IlmImfUtil PROPERTIES INTERFACE_LINK_LIBRARIES
                              "${OpenEXR_IlmImfUtil_LINK_LIBS};${OpenEXR_IlmImfUtil_LINKER_FLAGS_LIST}")
        set_target_properties(OpenEXR::IlmImfUtil PROPERTIES INTERFACE_COMPILE_DEFINITIONS
                              "${OpenEXR_IlmImfUtil_COMPILE_DEFINITIONS}")
        set_target_properties(OpenEXR::IlmImfUtil PROPERTIES INTERFACE_COMPILE_OPTIONS
                              "${OpenEXR_IlmImfUtil_COMPILE_OPTIONS_C};${OpenEXR_IlmImfUtil_COMPILE_OPTIONS_CXX}")
    endif()
endif()

########## GLOBAL TARGET ####################################################################

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    if(NOT TARGET OpenEXR::OpenEXR)
        add_library(OpenEXR::OpenEXR INTERFACE IMPORTED)
    endif()
    set_property(TARGET OpenEXR::OpenEXR APPEND PROPERTY
                 INTERFACE_LINK_LIBRARIES "${OpenEXR_COMPONENTS}")
endif()

########## BUILD MODULES ####################################################################
#############################################################################################
########## COMPONENT IlmBaseConfig BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IlmBaseConfig_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Iex BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_Iex_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IlmThread BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IlmThread_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IexMath BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IexMath_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT Half BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_Half_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IMath BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IMath_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT ilmbase_conan_pkgconfig BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_ilmbase_conan_pkgconfig_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IlmImfConfig BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IlmImfConfig_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IlmImf BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IlmImf_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
########## COMPONENT IlmImfUtil BUILD MODULES ##########################################

foreach(_BUILD_MODULE_PATH ${OpenEXR_IlmImfUtil_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
