

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                string(REGEX REPLACE "[^A-Za-z0-9.+_-]" "_" _LIBRARY_NAME ${_LIBRARY_NAME})
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findglad.cmake")
# Global approach
set(glad_FOUND 1)
set(glad_VERSION "0.1.34")

find_package_handle_standard_args(glad REQUIRED_VARS
                                  glad_VERSION VERSION_VAR glad_VERSION)
mark_as_advanced(glad_FOUND glad_VERSION)


set(glad_INCLUDE_DIRS "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/include")
set(glad_INCLUDE_DIR "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/include")
set(glad_INCLUDES "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/include")
set(glad_RES_DIRS )
set(glad_DEFINITIONS )
set(glad_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(glad_COMPILE_DEFINITIONS )
set(glad_COMPILE_OPTIONS_LIST "" "")
set(glad_COMPILE_OPTIONS_C "")
set(glad_COMPILE_OPTIONS_CXX "")
set(glad_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(glad_LIBRARIES "") # Will be filled later
set(glad_LIBS "") # Same as glad_LIBRARIES
set(glad_SYSTEM_LIBS )
set(glad_FRAMEWORK_DIRS )
set(glad_FRAMEWORKS )
set(glad_FRAMEWORKS_FOUND "") # Will be filled later
set(glad_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(glad_FRAMEWORKS_FOUND "${glad_FRAMEWORKS}" "${glad_FRAMEWORK_DIRS}")

mark_as_advanced(glad_INCLUDE_DIRS
                 glad_INCLUDE_DIR
                 glad_INCLUDES
                 glad_DEFINITIONS
                 glad_LINKER_FLAGS_LIST
                 glad_COMPILE_DEFINITIONS
                 glad_COMPILE_OPTIONS_LIST
                 glad_LIBRARIES
                 glad_LIBS
                 glad_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to glad_LIBS and glad_LIBRARY_LIST
set(glad_LIBRARY_LIST glad)
set(glad_LIB_DIRS "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/lib")

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_glad_DEPENDENCIES "${glad_FRAMEWORKS_FOUND} ${glad_SYSTEM_LIBS} ")

conan_package_library_targets("${glad_LIBRARY_LIST}"  # libraries
                              "${glad_LIB_DIRS}"      # package_libdir
                              "${_glad_DEPENDENCIES}"  # deps
                              glad_LIBRARIES            # out_libraries
                              glad_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "glad")                                      # package_name

set(glad_LIBS ${glad_LIBRARIES})

foreach(_FRAMEWORK ${glad_FRAMEWORKS_FOUND})
    list(APPEND glad_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND glad_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${glad_SYSTEM_LIBS})
    list(APPEND glad_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND glad_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(glad_LIBRARIES_TARGETS "${glad_LIBRARIES_TARGETS};")
set(glad_LIBRARIES "${glad_LIBRARIES};")

set(CMAKE_MODULE_PATH "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "C:/Users/julian.auriac/.conan/data/glad/0.1.34/_/_/package/473c24ae8996a862e6a24597d141497cb708b730/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET glad::glad)
        add_library(glad::glad INTERFACE IMPORTED)
        if(glad_INCLUDE_DIRS)
            set_target_properties(glad::glad PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${glad_INCLUDE_DIRS}")
        endif()
        set_property(TARGET glad::glad PROPERTY INTERFACE_LINK_LIBRARIES
                     "${glad_LIBRARIES_TARGETS};${glad_LINKER_FLAGS_LIST}")
        set_property(TARGET glad::glad PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${glad_COMPILE_DEFINITIONS})
        set_property(TARGET glad::glad PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${glad_COMPILE_OPTIONS_LIST}")
        
    endif()
endif()

foreach(_BUILD_MODULE_PATH ${glad_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
