#!/bin/bash

### script pour executer des jobs sur Cluster Cemef
### [ 04/2019 ]

### indiquer nombre de core et duree max de votre job hh:mm:ss
#OAR -l core=24,walltime=00:50:00
#OAR -p nbcores='24' and host='n-in6' or host='n-in7' or host='n-in8' or host='n-in9' or host='n-in10' or host='n-in11' or host='n-in12'
### indiquer le nom de votre job
#OAR -n abhishekp-job
#OAR -O oarlogs/%jobid%.out
#OAR -E oarlogs/%jobid%.out
JOB_DIR=$PWD/oarlogs
mkdir -p $JOB_DIR
### execution par oar de $MONPROG avec $MYDATA
### usage : oarsub -S ./job_exemple.sh
### usage : oarsub -l core=32 -S ./job_exemple.sh

### indiquer votre executable
## MONPROG=$PWD/bin/densemv_mpi.exe
MONPROG=$PWD/bin/spmv_mpi.exe
# MONPROG=/gext/jean-marc.gratien/ParallelProgrammingTP/bin/densemv_mpi.exe
### indiquer votre fichier de donnees
MYDATA=


### en execution standand, rien a changer ci-apres

echo DEBUT
date

NP=$(cat $OAR_NODE_FILE | wc -l)
echo execution sur $NP coeurs
echo sur les nodes $(cat $OAR_NODE_FILE)

#MPIRUN="/softs/mpi/openmpi-1.10.7/gcc-7.3.0/bin/mpirun \
#  -n $NP \
#  -machinefile $OAR_NODE_FILE "
 
MPIRUN="/softs/mpi/openmpi-4.0.1/gcc-7.3.0/bin/mpirun"

set -x
#export OMP_NUM_THREADS=1

if [ -f $MONPROG ] ; then
  if [ -f $MYDATA ] ; then
  for np in 16 24
## 1 2 4 8 12 16 24
  do
    for nx in 1000 2000 3000 4000 5000
    do
    $MPIRUN -np ${np}  $MONPROG --nx ${nx} > $JOB_DIR/log-NX${nx}-NPI${np}
    done
  done
  else
    echo "ERREUR : data $MYDATA inexistant !!"
  fi
else
   echo "ERREUR : programme $MONPROG inexistant !!"
fi


date
echo FIN
