#!/bin/bash

### script pour executer des jobs sur Cluster Cemef
### [ 04/2019 ]

### indiquer nombre de core et duree max de votre job hh:mm:ss
#OAR -l core=24,walltime=00:50:00
### indiquer le nom de votre job
#OAR -n job_exemple
#OAR -O %jobid%.out
#OAR -E %jobid%.out

### execution par oar de $MONPROG avec $MYDATA
### usage : oarsub -S ./job_exemple.sh
### usage : oarsub -l core=32 -S ./job_exemple.sh

### indiquer votre executable
MONPROG=/gext/rached.chaaben/ParallelProgrammingCourse/TPs/ParallelProgrammingTP/bin/densemv_mpi.exe
MONPROG2=/gext/rached.chaaben/ParallelProgrammingCourse/TPs/ParallelProgrammingTP/bin/sparsemv_mpi.exe
MONPROG3=/gext/rached.chaaben/ParallelProgrammingCourse/TPs/ParallelProgrammingTP/bin/life-of-boids

### indiquer votre fichier de donnees
MYDATA=


### en execution standand, rien a changer ci-apres

echo DEBUT
date

#NP=$(cat $OAR_NODE_FILE | wc -l)
#echo execution sur $NP coeurs
#echo sur les nodes $(cat $OAR_NODE_FILE)

#MPIRUN="/softs/mpi/openmpi-1.10.7/gcc-7.3.0/bin/mpirun \
#  -n $NP \
#  -machinefile $OAR_NODE_FILE "

#1 2 4 8 12 16 24
MPIRUN="/softs/mpi/openmpi-4.0.1/gcc-7.3.0/bin/mpirun -n $NP -machinefile $OAR_NODE_FILE"
BOIDS ="./bin/life-of-boids --mode $mode --n_th $n_th"
#set -x
#export OMP_NUM_THREADS=1


if [ -f $MONPROG3 ] ; then
  if [ -f $MYDATA ] ; then
  for mode in 1 2
  do
    for n_th in 1 2 4 8 12 16 24
    do
    $MONPROG3 --n_th ${n_th} --mode ${mode} >> log-boids
    done
  done
  else
    echo "ERREUR : data $MYDATA inexistant !!"
  fi
else
   echo "ERREUR : programme $MONPROG inexistant !!"
fi


date
echo FIN
