#!/bin/bash

### script pour executer des jobs sur Cluster Cemef
### [ 04/2019 ]

### indiquer nombre de core et duree max de votre job hh:mm:ss
#OAR -l core=24,walltime=00:50:00
### indiquer le nom de votre job
#OAR -n job_exemple
#OAR -O %jobid%.out
#OAR -E %jobid%.out

### execution par oar de $MONPROG avec $MYDATA
### usage : oarsub -S ./job_exemple.sh
### usage : oarsub -l core=32,walltime=00:00:60 -S ./run 

### indiquer votre executable
MONPROG=bin/life-of-boids_TBB

### en execution standand, rien a changer ci-apres

echo DEBUT
date

if [ -f $MONPROG ] ; then
  for nb in 1 2 4 8 12 16 24
  do
	$MONPROG --nb-threads $nb # > log-NX${nx}-NPI${np}
  done
else
   echo "ERREUR : programme $MONPROG inexistant !!"
fi

date
echo FIN